### ISSUE TITLE
Update to Django Rest Framework 3.0 ?

### ISSUE THREAD

**Issue by martinfilliau** [ox-it/talks.ox#156]
Big release of django-rest-framework, might be worth upgrading before going further

See http://www.django-rest-framework.org/topics/3.0-announcement/

**Comment by martinfilliau** [comment]
See #186

**Comment by ahaith** [comment]
The CollectionItemSerializer which saves talks or series to the (Talks) user's collection no longer works with 3.0. I think it should be possible to fix with some refactoring though.
