### ISSUE TITLE
Series Editing

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#182]
Here:

https://talks-dev.oucs.ox.ac.uk/talks/series/id/43ac1919-eb0a-4240-b8cb-b253da80c5f3/edit

Were we meant to be able to add a person - I think the reason we took organiser off the modal was so that we could make it possible to add a person who wasn't on the list.

**Comment by ahaith** [comment]
See #128 - it was requested to be hidden when creating, but I don't think that's necessary now.

**Comment by ahaith** [comment]
@envycontent. Is there any reason not to have multiple organisers for an event series? It would be a little easier to implement this if there can be multiple of them.

**Comment by envycontent** [comment]
I can't think of a reason, multiple would be fine therefore.

Anne
