### ISSUE TITLE
Feature Parity with Old System

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#185]
Main information is here:

https://docs.google.com/document/d/1BhkWtDgDEApzC3HAezLo5FLT9oloVbGI3smT8pg9FWY/edit#heading=h.g7pg1e48n51h

**Comment by martinfilliau** [comment]
@envycontent from what I can read it sounds like we have reached feature parity -- but it is not compatible with the current API for obvious reasons: we do use the same vocabulary for lists (oxpoints, FAST topics...)

See documentation http://talksox.readthedocs.org/en/latest/http_api/endpoints/Search/events_search.html

If you're ok with this then I think we can close this issue?

**Comment by envycontent** [comment]
Thanks - I will check and play over the next couple of days.

Anne
