### ISSUE TITLE
Field for sharing editing

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#196]
I think we are using 'Talk Organiser'  rather than 'Event Organiser' for people who have been given that role. I'm still a little bit concerned that this is going to cause confusion. We add people to the database who are organisers of talks or events but they don't have to have the Talk Organiser role.  It isn't too late to change this in the UI and the documentation and I'm wondering if Talks Editor might be a better option as it would differentiate it in people's minds.

Could we change the wording

Other Editors

Share editing with another Talks Editor by typing in their email address

**Comment by ahaith** [comment]
Actually, we are using 'Other event organisers who can edit this event', which is right at the bottom of the page. This is a list of database Users with permission to edit the event.

As it currently stands, there is also an 'Organisers', field which is a list of Persons - just names and bios as for Speakers / Hosts. I agree this is confusing. Should this field really be here?

**Comment by envycontent** [comment]
Ha ha

Yes, I think you've got confused exactly as I thought.

We can't assume that the organiser of the event/talk is actually going
to be signed up as a user and editing the item. It could be someone
completely different.

So we need a field to specify the person who actually organises the event.

We also need a role with rights to create and edit and to share the item
with someone else. We're calling that role 'Talk Organiser' at the
moment, but I think it is misleading as it leads to confusion with the
real organiser.

Anne

**Comment by ahaith** [comment]
Ha. I see - so there is a need for a non-user Organiser.
I'll amend the language as you suggest so there aren't any other misleading references to 'organiser'

**Comment by envycontent** [comment]
Great, I'll change things in the documentation as well. I think the
confusion may have arisen because I did the specs as user stories - but
I'm not going to think too hard as it hurts my head :-)

Anne
