### ISSUE TITLE
UI: Viewing all talks in a group

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#198]
It would be useful to have a quick route to seeing all the talks in a group and then clicking through to the edit form. e.g. you can get here:

https://talks-dev.oucs.ox.ac.uk/talks/series/id/f92ac5b7-c06d-4cb6-9f0b-38f1f5f83af2

but you then need to click through to view each talk before you edit it (and you don't know if it is 'In preparation' etc) before you click through.

Most people will be editing talks per group.

**Comment by envycontent** [comment]
Just to clarify - I'm documenting the dashboard at the moment and how it helps specifically with scheduling in talks before you have all the details.

**Comment by envycontent** [comment]
Actually the quickest way to sort this would be to have the Series or Group title in small letters underneath the Talk title on the dashboard, and then order the talks in the dashboard by Group, then Date

**Comment by ahaith** [comment]
Before seeing your last comment, I'd already started updating the 'show series' view to include the published status and an edit button (only for Contributors).

I've just deployed that to talks-dev so you can take a look and let me know if that's enough.

**Comment by ahaith** [comment]
It also occurs to me that we probably don't want non-Contributors to see unpublished events in the series view, although currently they can. I'll go ahead and hide them for non-Contributors if you agree.

**Comment by envycontent** [comment]
Yes, that sounds good. I thought that too.

Anne

**Comment by envycontent** [comment]
Adding the edit button looks perfect. Thanks. I'll document now.

**Comment by ahaith** [comment]
Great. Unpublished talks are also now invisible to non-contributors.
