### ISSUE TITLE
UI: Dashboard - missing properties

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#199]
1. Could the title of this be changed to 'Missing Information' - properties is a bit of a techie term.

2. The 'All' option is a bit confusing - particularly as there might be a number of fields intentionally left blank. Perhaps remove this as it probably isn't that helpful.

3. Could we have a Speakers option here as well?

**Comment by envycontent** [comment]
Ah I understand, the 'All' turns the filters off. I'm more used to a tick box toggling each term. Can I add that to the wish list.

**Comment by envycontent** [comment]
Additional thought: perhaps change 'All' to 'Remove Filter'

**Comment by envycontent** [comment]
Further thoughts:

4. Could Title TBA be changed to Untitled Talks
5. Could Location be changed to Venue

This would make things a bit more consistent.

**Comment by ahaith** [comment]
Another option: We could remove the 'All' buttons altogether, and just put an 'X' button next to any active filters to clear them.

**Comment by envycontent** [comment]
On 13/01/2015 11:12, Andy Haith wrote:
> Another option: We could remove the 'All' buttons altogether, and just
> put an 'X' button next to any active filters to clear them.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ox-it/talks.ox/issues/199#issuecomment-69729367>.
> 

Perfect - if that's possible.

Anne

**Comment by ahaith** [comment]
I couldn't do the 'remove filter' exactly as described, but I think what's there now should be much more intuitive.

**Comment by envycontent** [comment]
Can't see yet on dev, but from a quick look at the commit that seems like it will be much better. Thanks.

**Comment by ahaith** [comment]
There's an issue preventing us from deploying to dev at the moment. But here's a preview:
![screen shot 2015-01-13 at 16 30 20](https://cloud.githubusercontent.com/assets/6075037/5724142/845c46e8-9b41-11e4-9ea8-bfb44583e590.png)

**Comment by envycontent** [comment]
Superb!
