### ISSUE TITLE
UI: Dashboard - order of talks

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#200]
Is there any logic to the order of talks on the Dashboard? Date order might be a good option.

**Comment by ahaith** [comment]
They're currently in order they were entered. I've tried doing it in date order but this floods the list with old talks from the past.
To avoid this, we could either default to only showing Future Events, or else order them by 'decreasing' date.

**Comment by ahaith** [comment]
While we're discussing ordering, is it sensible to sort Series by title and Persons by surname?

**Comment by envycontent** [comment]
It might make sense to show only future events by default, as,
realistically, we're unlikely to want to edit many past talks.

**Comment by envycontent** [comment]
Yes
