### ISSUE TITLE
Sharing series

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#204]
Is it possible to share editing of an entire series? There isn't a field on the Series edit form to do this.

If it is possible (hope it is) will sharing propagate to the talks assigned to that series?

**Comment by ahaith** [comment]
See also #205
Currently anybody who is a Contributor can edit any series - there isn’t currently any concept of an owner or editor for a Series.

If it is necessary to restrict editing of a series, we would propose a similar solution to the sharing of editing of events, as follows:
- Each Series has a list of Editors, as for Events
- A Series' details can only be edited by one of these Editors
- The Dashboard list of series can be filtered to show only those which are editable by the current user
- A Series Editor can edit any Talk within the series, whether or not they are on the individual Editor list for that talk
- A Talk Editor can only add a Talk to a Series of which they are also an editor

Questions and concerns:
- Series Editors will only be able to add Talks for which they are also an Editor. Is this OK?
- A Talk Editor will continue to be able to edit a Talk which is part of a series, except that they won’t be allowed to change the Series unless they are also an Editor for the Series. Is this OK
- A Talk Editor will only see Series they can edit in the drop-down list when attempting to pick a Series for a talk, and will see a blank list if they are not an Editor on any Series. Is it OK to explain that with help text and a label?

We’re estimating a total of 2 days’ work to implement this

**Comment by envycontent** [comment]
This is required for feature parity with the old system so I think it
needs to be done. However, I have emailed Ted and Sebastian about it
just to double-check that they are OK to go ahead with it funding-wise.

Will it be possible to get this done before launch?
