### ISSUE TITLE
Person

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#206]
Just to mention that as a contributor, I can edit any person in the system. I think that is OK - if you think that is OK, then please assign the ticket to me and I will write some documentation and also request the inclusion of a warning explaining that changing the text will affect all entries in all talks.

**Comment by martinfilliau** [comment]
I think that it is OK; otherwise might create a complex and maybe too restrictive system?

**Comment by martinfilliau** [comment]
Leaving it to @envycontent to add some documentation

**Comment by envycontent** [comment]
WIP at the moment - coming soon.
