### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#207]
I've noticed a lack of a Cancel button. This is fine if intentional, and I will document hitting the back button - please assign the ticket to me if that's the case.

**Comment by martinfilliau** [comment]
What would this Cancel button do?

**Comment by envycontent** [comment]
In this case I had started making some changes to a talk, but realized
they were wrong and wanted to back out - usually a form has a Cancel
button - which would usually take you out of edit and back to view
without changing anything.

It took me a few moments to work out that I needed to use the back
button in my browser. Having said that:

http://www.nngroup.com/articles/reset-and-cancel-buttons/

(dated 2000)

I'll document using the Back button as per the ticket assignment.

Anne
