### ISSUE TITLE
Removing Shared Editors

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#208]
1. If Person N shares a talk with Person A, Person A can remove Person N from the talk.

(We discussed this and thought this would be OK as Person N might move jobs or something - however....)

2. If Person N creates a talk they can also remove themselves as an editor from the talk, even if they are the only editor. This leaves the talk in a bit of a limbo as only the superuser can then edit it.

If this is OK with you, then I'll document it - assign ticket to me

**Comment by ahaith** [comment]
The user who presses save will always be added to the editors list for talk (even if they try to remove themselves from the list), so it shouldn't be possible to leave a talk in editor-less limbo.

**Comment by envycontent** [comment]
Is that the actual behaviour or the proposed behaviour? When Nicole
tried this yesterday she was locked out of the talk she'd removed
herself from.

Anne

**Comment by ahaith** [comment]
Sorry - we thought that was the current behaviour, but we were mistaken. We should be able to make it work like that however, if that sounds ok.

**Comment by envycontent** [comment]
Yes, sure. If it isn't possible I can document it as a .. warning:: (or
whatever the reST syntax is) and then point them at the help desk to
unlock it.

Anne

**Comment by martinfilliau** [comment]
Done & deployed
