### ISSUE TITLE
Wishlist: emails and urls in the abstract

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#216]
It would be really nice to be able to side step the slightly clunky formatting of emails and urls in Textile and just allow people to enter the raw email or url and have that marked up automatically.

**Comment by martinfilliau** [comment]
Should set `auto_link` to `True` when calling `textile_restricted` in `Event.description_html`.

See https://github.com/textile/python-textile/blob/master/textile/core.py#L1650

**Comment by martinfilliau** [comment]
@envycontent done and deployed, see https://talks-dev.oucs.ox.ac.uk/talks/id/fc1cfd72-c450-450e-8fed-25ab39ee3928/ for instance; however that does not work for email addresses and would probably require some custom work; I'll let you decide how much it is a priority or absolutely necessary...

**Comment by envycontent** [comment]
Email addresses aren't a priority - I'll document how to do it - it may
make them think twice before they do publish an email.
