### ISSUE TITLE
Wishlist: Calendar widget

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#220]
I've finally twigged that the calendar is defaulting to the exact Date and Time of Now - this is disconcerting because once you've selected an hour, it then defaults to whatever minutes past the hour it is right now.

Any possibility that it could default to today's date and 11am ?

Assign to me if impossible and I'll document it as a known bug (or just suggest that people only do entering of talks on the hour).

**Comment by ahaith** [comment]
It now defaults to 11am today.
N.B. I've discovered that it's possible to restrict the 'minutes' view to a custom increment.
e.g. only offer every 15 minutes as the start time - see screenshot. Is this desirable?
![screen shot 2015-01-21 at 15 04 58](https://cloud.githubusercontent.com/assets/6075037/5838603/71425468-a180-11e4-98b3-68aa8cadc0e1.png)

**Comment by envycontent** [comment]
Magic! I think the minutes restriction is attractive but bound to lead
to problems (unless the time is then editable manually). Doubtless
someone will have something that starts at 10 past. As long as it
defaults to 00, they should be OK.

Anne
