### ISSUE TITLE
New Talks -> Old Talks: Series

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#227]
Would it be possible please to expotr the following fields to the Series Description in Old Talks:

Series Description
Series Organiser (s)

I will hide the paragraph on old talks that shows the api_user as a contact

**Comment by martinfilliau** [comment]
@ahaith would be great if you could do this one and #228 to see how it is working... https://github.com/ox-it/talks.ox/tree/master/talks/old_talks

**Comment by martinfilliau** [comment]
Done & deployed
