### ISSUE TITLE
New Talks -> Old Talks: Talk

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#228]
1. Please could the following fields be appended to the description/abstract

Talk hosts
Talk organisers
Contact email

Audience
Booking required
Booking email / Web address
Cost

(these are all items that are currently put into the abstract in Old Talks because there is nowhere else to put them)

2. Please could the affiliation for a speaker be appended to the speaker's name

3. Please could the venue details be appended to the venue name

4. Please could the special message be copied across

Thanks! I will hide the reference to the API user on old talks

**Comment by martinfilliau** [comment]
@ahaith I think that the following is still missing?
* [ ] Please could the affiliation for a speaker be appended to the speaker's name
* [ ] Please could the venue details be appended to the venue name

**Comment by ahaith** [comment]
Is special message its own field on the old talks, or should it just be appended to the abstract?

**Comment by martinfilliau** [comment]
Sounds like you can use `special_message` https://github.com/ox-it/talks-oxford-talks-ruby/blob/master/app/models/talk.rb#L77 <https://github.com/ox-it/talks-oxford-talks-ruby/blob/master/app/models/talk.rb#L77>

Should test it.

**Comment by ahaith** [comment]
'special_message' works nicely
