### ISSUE TITLE
Logging in and out

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#239]
I seem to be logged in between browser sessions now (Chrome and Firefox on Mac) - I don't think that was happening before. Is that deliberate and if so, how do you logout?

Also, should there be a link to log in?

**Comment by martinfilliau** [comment]
Not sure to understand "logged in between browser sessions" ?

Logout should be at `/logout`, we could indeed have a login/logout link... what's the best place for it?

**Comment by envycontent** [comment]
Sorry, should have been clearer. I completely closed my browser but when
I opened my browser again I was still logged in - this was a bit
unexpected as for most apps I usually expect webauth to ask me to log in
again when I reopen my browser - perhaps ask Ted as to what is most
appropriate, although it is nice to be logged in immediately I open my
browser it is maybe a bit of a security issue with SSO?

I've just looked at Ted's wireframes [1] and can't see a login button.
However, I reckon the obvious place would be next to the Add Talk
button. This is probably something Ted ought to decide though.

[1]
https://drive.google.com/folderview?id=0B2IDH8ZG9tYRa3FjUVJWRS1CdHM&usp=sharing

**Comment by martinfilliau** [comment]
Regarding the length of the session, we can adjust the settings if it is required, will leave it to @tkoterwas for both questions

**Comment by tkoterwas** [comment]
I'd say a sign in button just to the left of the search box.

regarding session length, it seems for most sso services I need to sign in once a day. That seems reasonable to me. 12 hours?

**Comment by envycontent** [comment]
Logout would be great too. I tried logging out and it took me through a proper webauth logout so that was great.

**Comment by martinfilliau** [comment]
Session timeout done in a21dc82ec282bcc34a2b913ef7c66a96d431fef2, will do the links this afternoon.

**Comment by martinfilliau** [comment]
Done and deployed
