### ISSUE TITLE
Demo Widget: Sort Order | Empty fields

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#243]
I'm not sure whether these two points should be dealt with in the API or the widget - will leave you to determine.

1. Talks are randomly sorted. Ideally it would be good to offer an Order By option or at least sort in ascending start date order.
2. Title TBA results in an empty field <title /> in the XML/JSON - should the widget check for this or 'To be Announced' be included in the feed.

**Comment by martinfilliau** [comment]
@envycontent regarding your two questions:
   1. you're right, the results from the API are not currently sorted; I would suggest for now to "hardcode" the sorting by asc start date. We (you) could eventually introduce more sorting options later via a query parameter however I'm not entirely sure what could be the alternative choices at the moment and would keep it simple.
   2. you're right again, however I wouldn't impose "Title to be announced" to all the API's client as they would not be able to easily differentiate it from "real" titles -- and they might want to handle it differently. I would suggest to just document the fact that the title might be blank. Tell me if you're OK with that; the demo widget could then be updated.
Issues specific to the JS widget can be contributed directly in https://github.com/ox-it/talks.ox-js-widget/issues

**Comment by envycontent** [comment]
re 1. Sounds good. re 2. Also sounds good. I will experiment some more
and submit issues to the right place :-)

Anne

**Comment by envycontent** [comment]
Submitted issue here:

https://github.com/ox-it/talks.ox-js-widget/issues/7

**Comment by martinfilliau** [comment]
Closing this issue as new issue has been created in relevant repository.
