### ISSUE TITLE
Duplicate entries from API

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#246]
See https://github.com/ox-it/talks.ox-js-widget/issues/10

Searching for two topics which happen to be assigned to the same talk brings that talk up twice in the search results. Not sure if that is intentional, but probably not what people would want in the widget (on the other hand, this might not be a typical use-case)

e.g ['http://id.worldcat.org/fast/1097048','http://id.worldcat.org/fast/864329']

**Comment by martinfilliau** [comment]
Definitively not intentional, suspect we should use a DISTINCT clause.
