### ISSUE TITLE
Need a favicon.ico

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#247]
@envycontent I presume we want the same icon as the old talks - i.e. the oxford crest:
http://talks.ox.ac.uk/images/favicon-ox-uni.ico?1422353714

**Comment by envycontent** [comment]
Yes, I think that's standard for University websites.

Anne

**Comment by ahaith** [comment]
@drewhemm Any chance you could sort this out when you have a moment?

**Comment by vladigor** [comment]
Done; will deploy to dev next week
