### ISSUE TITLE
API links target prior to Phase 2

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#248]
Before the new talks site becomes the public interface for talks.ox, we probably want the links returned from the API to point at the relevant old talks pages.

**Comment by envycontent** [comment]
Yes it is fairly simple:

http:/talks.ox.ac.uk/talk/index/[talk_id]

http://talks.ox.ac.uk/show/index/[series_id]

**Comment by envycontent** [comment]
I'm closing this as pointing to the old talks site is no longer necessary.
