### ISSUE TITLE
Error messages for unavailable old talks urls

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#249]
After we roll out the new site as talks.ox.ac.uk, if a user tries to follow a link for the old site, they'll just get a 404.
We should be able to detect url patterns for old talks and show a helpful message suggesting they search or browse the new site to find what they were looking for.
It should also be possible to automatically redirect from urls for any talks/series which were entered via the new site, as we'll have the old talks ids available for those

**Comment by martinfilliau** [comment]
> After we roll out the new site as talks.ox.ac.uk, if a user tries to follow a link for the old site, they'll just get a 404. We should be able to detect url patterns for old talks and show a helpful message suggesting they search or browse the new site to find what they were looking for.

Agreed, we should have a look to the Apache logs to see what are the current patterns, and provide a more helpful 404 page.
> It should also be possible to automatically redirect from urls for any talks/series which were entered via the new site, as we'll have the old talks ids available for those
> 
Yes indeed you could create `views.py` and `urls.py` in `old_talks` to plug some URLs which mimic the current path (i.e. `talks/index/X`) and do a permanent redirection thanks to the correspondance we keep in the `OldTalk` and `OldSeries` models.

**Comment by envycontent** [comment]
Depending on when we roll out the new site, this may not be a huge
issue. Users tend to look forwards to upcoming events rather than
backwards to past events, so there may not be much of a need to support
old site links.

**Comment by vladigor** [comment]
Mappings for old talks and series have been added.  Requests to old talk/series urls will result in a 403 response redirecting the user to the new talk/series page.
