### ISSUE TITLE
Link to user guide

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#255]
Occurred to me that we might need a link to the user guide on the site?

http://talksox.readthedocs.org/en/latest/

**Comment by martinfilliau** [comment]
![screen shot 2015-02-05 at 15 23 01](https://cloud.githubusercontent.com/assets/21462/6062885/0dc67d7a-ad4b-11e4-8ef9-564a0c1fb9d5.png)

@envycontent have a look to talks-dev.oucs.ox.ac.uk, the link only appears if you're a talk administrator

Could you reopen the issue if you prefer the link or behaviour to be different.
