### ISSUE TITLE
Formating abstracts

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#256]
Hello
I documented  the abstract field as accepting Textile markup - however it doesn't seem to parse it - see 
https://new.talks.ox.ac.uk/talks/id/153bfdb2-8738-43b2-affb-bb41d61f8445/

Did this get changed?

**Comment by martinfilliau** [comment]
@envycontent the `*Test*` is emphasising correctly, gonna investigate

**Comment by martinfilliau** [comment]
@envycontent now fixed. It actually never worked, there was a restriction which was only authorising "block tags to p, bq, and bc, disable tables".
Deployed.

**Comment by envycontent** [comment]
Could this be set for Series abstract as well :-)

**Comment by martinfilliau** [comment]
Sorry, now done and deployed.
