### ISSUE TITLE
Updating new to old

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#257]
I'm seeing one potential wrinkle - I can document but it might catch people out.

1. Create a new series -> appears in Old Talks
2. Create a talk and assign to the series -> appears in Old Talks
3. Create a talk but don't assign it to a series -> doesn't appear in Old Talks
4. Edit talk and assign it to the series -> doesn't appear in Old Talks

1 to 3 are expected behaviour, for 4 you'd expect the talk to now appear in Old Talks

**Comment by martinfilliau** [comment]
@envycontent not sure to understand, if you create a talk with no series, it should appear on Old Talks. 4. should do so as well (the 4 cases should all appear to Old Talks, but it will be ex_directory if the status is not published)

**Comment by envycontent** [comment]
Hum, let me check :-)

**Comment by envycontent** [comment]
OK:

https://talks.ox.ac.uk/show/index/17501 is the series
https://talks.ox.ac.uk/talk/index/20397 is the talk created as under point 2 above
https://talks.ox.ac.uk/talk/index/20396 is the talk created as under points 3/4 as is also
https://talks.ox.ac.uk/talk/index/20398

Is it something to do with the odd thing about the database - where there is a many to many table list_talks and also a series_id on the talk itself?

Or is it that I can't see certain talks (although as I'm admin I ought to be able to see everything)

**Comment by martinfilliau** [comment]
Not sure if I understood everything but one issue I see in our code is the following:
`if series_id:
        data.append(("talk[series_id_string]", series_id))`

There is no `else` condition so if the talk *was* affected to a series but is not anymore then it might never be propagated to Old Talks depending on how it works. So it probably should make sure that `series_id` is `None` if there is no series.

We only use `series_id` and not the `list_talks` AFAIK.

**Comment by envycontent** [comment]
Ok, so the odd thing is that I can only see one talk listed under this series:

https://talks.ox.ac.uk/show/index/17501

but if you go to the other test talks I created e.g.:

 https://talks.ox.ac.uk/talk/index/20398

you can see them and they say they belong to the series but they aren't listed under the series here:

https://talks.ox.ac.uk/show/index/17501

However, I've looked at the database and searched for 17501 in the list_talks table. I found just one entry: 

| id | list_id | talk_id |
| 24934492 | 17501 | 20397 |

So I'm wondering whether on talk creation a row gets created automatically, but on talk update it doesn't.

(note the ID is an auto-increment field and started at 1 - so no wonder the database is a bit slow sometimes)

**Comment by martinfilliau** [comment]
Should be fixed on talks-dev now, will check further tomorrow morning and deploy on prod.

**Comment by envycontent** [comment]
Thanks. I'll test first thing.

**Comment by ahaith** [comment]
Is this fixed now?

**Comment by envycontent** [comment]
I think so - we'll find out when/if it breaks :-)

Anne
