### ISSUE TITLE
Add series to search index

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#262]

**Comment by martinfilliau** [comment]
I assume that you mean adding the series' title to every talk rather than searching for series?

Searching for series might be a fair bit of work as you'd have to search on two different types of things.

**Comment by ahaith** [comment]
I can imagine it would be helpful to be able to search on series description (or people, or venues...), but yes, that is a non-trivial task, and I don't think it's been specifically called out as a requirement.
Just adding the series title for each talk is probably a sensible step however.
