### ISSUE TITLE
Add timeout for pushing to old talks

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#264]
Currently we wait indefinitely for a response from old talks. We should add a (generous) timeout and display a helpful message to the user to explain what has happened if this is exceeded.

It may also be worth recording which talks failed to push, and perhaps attempting to push any unsynced talks again later.

**Comment by envycontent** [comment]
I've had the impression that NSMS have started monitoring old talks and
restarting when it starts to run out of memory so possibly any timeout
is likely to be relatively shortlived (a few minutes or so).

If it is possible to add a timeout that would be good. Is it feasible to
send errors to the RT queue? We have a specific email address for errors
from the aggregator - I'll dig it out. This would mean that I could
double-check any possible problems as they arose.

Anne

**Comment by ahaith** [comment]
There's now a timeout in place, with a helpful warning message to the user.
I'll look into sending an email, but in the meantime the audit trail may help in identifying which edits didn't make it across.
