### ISSUE TITLE
Make it more obvious to add a talk to a specific series

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#266]
Often as a Talks Organiser you are likely to be looking at the overview of a series and wanting to add a talk to that specific series e.g.:

https://new.talks.ox.ac.uk/talks/series/id/4816a263-4f16-4a07-919e-26d4baa736d8

The obvious thing to do is click Edit, but that just allows you to edit the series details. Add New Talk at the top of the screen isn't quite as obvious. Would it be feasible to have a Add New Talk to Series button. If this also automatically supplied the series ID to the new talk that would be lovely but not 100% necessary.

In the meantime I will document the process of adding a talk to a series.

**Comment by envycontent** [comment]
Would it be possible for the organising department to be pre-populated as well as the series? As per #210

**Comment by ahaith** [comment]
Done and deployed to production
