### ISSUE TITLE
Venue details don't map across to Old Talks if the venue itself is empty

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#267]
If a venue does not exist in the database, we are instructed to leave Venue blank and fill in Venue details instead (http://talksox.readthedocs.org/en/latest/user/talk-editors/create-a-talk.html#venue).

However, when this is done, the venue shows as "no list" in the old Oxford Talks website.

**Comment by mans0954** [comment]
Has this been pushed to production yet? It still seems to be an issue. Thanks.

**Comment by envycontent** [comment]
I think this has now been deployed
