### ISSUE TITLE
Oxpoints lookup problems in IE

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#269]
Seem to have a problem with IE 9.0.8112 - oxpoints look up doesn't give any results. 

(There are a number of IE 9 users in the University because the finance system works with that version and people don't want to mess with their setup)

**Comment by ahaith** [comment]
So there are no suggestions when they start typing in Venue or Organising Department?
Do the other suggestion fields work? (Topics, Person, Editors)?

**Comment by envycontent** [comment]
No for topics
yes for organisers

**Comment by martinfilliau** [comment]
Likely due to be caused by CORS not being properly supported by IE 9
unfortunately... (Places/Organisers are served by a different domain)

(Still receiving emails because this is a public repo)

**Comment by envycontent** [comment]
I can document this if necessary and encourage people to use another browser for editing.

**Comment by ahaith** [comment]
I'm going to look into a solution for this today. Thanks for the pointer @martinfilliau!

**Comment by ahaith** [comment]
Now using a small jquery plugin which fixes this.
