### ISSUE TITLE
Timeout for editing

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#271]
I seem to be hitting the time-out quite a lot - but there doesn't seem to be any indication that the old Oxford Talks is struggling (e.g. if I go to the site and click around it is reasonably responsive). Could the time out be a bit longer - i.e. to account for the fact that Oxford Talks can be sloooow.

**Comment by ahaith** [comment]
It's now 30s. Awaiting deployment.

**Comment by ahaith** [comment]
Was 10s, now 30s.
Deployed to production.
