### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#272]
There isn't any documentation for 'search' - as per that used in the javascript widget example. Would you trust me to write some along the lines of the existing API docs - I can submit for approval first?

**Comment by ahaith** [comment]
The 'search' endpoint is listed on the 'retrieve talks' page of the documentation. I think it probably merits being on its own page however.

**Comment by envycontent** [comment]
Ha, so it is! Assign to me if you want me to rejig that.

Anne

**Comment by ahaith** [comment]
I think it'd make more sense that way. Thanks!

**Comment by envycontent** [comment]
Done.
