### ISSUE TITLE
Series View with large number of Talks

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#277]
As time goes on, some series will have a large number of talks in them. This will mean that users will have to scroll through a long list to see the upcoming. I think we might hit this problem sooner rather than later, with editors a bit frustrated as they have to scroll through Hilary Term talks to see the talks for Trinity.

The old Oxford Talks gets round this by showing only upcoming talks, in ascending date order, and having an archive view for past talks (in descending date order).

**Comment by envycontent** [comment]
I've classified this as a bug - really it is a usability 'issue' - it isn't obvious now, but it will be fairly soon.

**Comment by ahaith** [comment]
@envycontent I've implemented a button to show all/upcoming on this page, and deployed it to staging. Please take a look and let me know what you think.

**Comment by ahaith** [comment]
I think it perhaps needs to say something specific if there aren't any upcoming talks, but there are some past ones.

**Comment by envycontent** [comment]
Looks great!

I think just 'No upcoming talks to display' seems fine. Not sure if we
need to ask them to press the button as well - as it is pretty obviously
positioned just below. I've just checked as well with my colleague who
specializes in documentation and, if you can do something with a mouse
or a finger the correct term is 'click' but if only with a finger then
'tap'. So it might be better to say 'Click Show all talks'.

Anne
