### ISSUE TITLE
Corrections to search.rst

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#280]
I've noticed a couple of things to be corrected here:

http://talksox.readthedocs.org/en/latest/http_api/endpoints/search.html

(line numbers are the relevant lines in the rst source file)

L13:

GET /api/events/search?from=today&topic=X HTTP/1.1
Host: talks.ox.ac.uk
Accept: application/json

L27    "href": "http://127.0.0.1:8000/api/talks/search?from=01/01/01"

L97  :query speaker: Search for talks at which the specified person is a speaker. Supply the unique slug for the person e.g. 'james-bond'

Assign to me if you're happy with them being corrected. 

I've discovered that the extension: http://sphinx-doc.org/ext/extlinks.html should do a better job of 'aliasing' links to talks.ox / new.talks.ox so will implement that if you have no objections.

Am trying to work out why the markup in the source file indicates the parameter type but this isn't rendered by Sphinx. Is there a house style for parameters? I've used numPy but noticed also this:

http://sphinxcontrib-napoleon.readthedocs.org/en/latest/index.html

**Comment by ahaith** [comment]
Yes, I agree with all of that. It might be worth adding some further explanation here too on how to find out things like a topic ID, a person slug, an oxpoints ID.

Please feel free to experiment with the documentation. The parameter types do show up in the Mobile Oxford API documentation, but I'm not sure offhand what the difference is - they're specified in the same way. See e.g. http://moxie.readthedocs.org/en/latest/http_api/endpoints/places.html
It does have a couple of extra extensions specified in the config file at https://github.com/ox-it/moxie/tree/master/docs:
`extensions = ['sphinx.ext.autodoc', 'sphinx.ext.todo', 'sphinx.ext.ifconfig', 'sphinxcontrib.httpdomain',]`

**Comment by envycontent** [comment]
Thanks, I'll do those corrections first, then I'll check the extensions
and I'll ask Alex as well about standards for parameters.

Anne
