### ISSUE TITLE
Person affiliation

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#283]
Two people have now commented that it is very awkward to have to add an affiliation when adding a new person. We wanted the affiliation to disambiguate between common names, but I wonder if we should take the risk of duplicates for ease of editing?

**Comment by ahaith** [comment]
Perhaps we could add a filter on the Persons Dashboard to show all people missing an affiliation?

**Comment by envycontent** [comment]
Might be a good idea if it is do-able.

**Comment by ahaith** [comment]
Done in master.
