### ISSUE TITLE
User Admin Interface

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#289]
Is it possible to add columns to the table here?:

https://new.talks.ox.ac.uk/admin/auth/user/

It would be helpful to have a column with the First Login Date and also if the user has Contributor status.

I'm finding it difficult to distinguish new users and also those users who ought to have Contributor status but don't. (i.e. you can filter by Contributor, but not by NOT Contributor)

**Comment by envycontent** [comment]
Would be helpful to have this done by service transition but affects very few people at the moment.

**Comment by vladigor** [comment]
Done
