### ISSUE TITLE
Ordering speakers

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#294]
If there are one or more speakers it isn't possible to change the order in which they are listed (not sure how we/I managed to miss that one).

The work around for this is to enter the speakers in the order in which they are going to appear. However, users say this is apparently then trumped by the display which lists them in alphabetical order.

**Comment by ahaith** [comment]
Just had a little look into this.
I had hoped that the personEvent IDs could be used to order them in the order they were added to the event. However, when the form is actually submitted, the speakers are ordered by their own person ID when the form is serialised.
It may be possible to intervene here and/or store some supplementary data to specify the desired order, but I don't think it is straightforward unfortunately.

**Comment by envycontent** [comment]
This would be something it would be helpful to tackle in due course - as sometimes the ranking of speakers in an individual event can be important.
