### ISSUE TITLE
Adding series to the Search API

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#300]
I have started to make use of the API and have noticed something interesting:

1. You can't search for a series, you can only use the api/series/id query
2. If you use api/series/id there's no documentation as far as I can see to restrict the time range of the talks

It would be very helpful to add series to the search API because:

1. You can't use the widget to show just one seminar series at the moment
2. If you are very clever and find a way to use the api/series/id you may end up with a very long list of past talks
3. The widget could also be used to show multiple seminar series - thus providing a sort of substitute for an aggregated list of lists 

The widget therefore doesn't quite do the job of replacing the variety of templates that the old Oxford Talks offers - would be good to add the option as the sooner we can encourage use of the widget the sooner the old Oxford Talks can be retired.

**Comment by ahaith** [comment]
I've added this functionality to the API and deployed to staging. You can see it in action with this link:
https://talks-dev.oucs.ox.ac.uk/api/talks/search?from=01/01/01&series=97e69afe-d82c-458c-907f-5cd4b0eb1996

Next I'll update the documentation and widget.

**Comment by envycontent** [comment]
Thanks Andy - that's fantastic!

Assign the documentation to me if you like.

Anne

**Comment by alexsdutton** [comment]
Can we use ISO 8601 dates, please? e.g. 2001-01-01

**Comment by envycontent** [comment]
May we please parse the old version dates as well, given that some
people may already be using the API/widget and get caught out.

(which leads me to ... should we be officially versioning the API... or
is there a route to communicate changes)

re-assign the ticket to me when you're ready and I'll document changes.

Anne

**Comment by alexsdutton** [comment]
`dateutil`'s [`dateutil.parser.parse`](http://dateutil.readthedocs.org/en/latest/parser.html#dateutil.parser.parse) can handle various formats, if you feel like adding another dependency. ;-)

**Comment by ahaith** [comment]
@alexsdutton I've opened a separate issue about date format.
The widget has now been updated, so assigning to Anne to update the documentation.

**Comment by envycontent** [comment]
Any chance this could be deployed to production (before I document it?)

**Comment by ahaith** [comment]
Now deployed to production.

**Comment by envycontent** [comment]
Thanks, I've taken the ticket to document.
