### ISSUE TITLE
Generating iCalendar

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#306]
There will be more to add to this issue as Nicole and I are going to test out the iCalendar stuff today. It looks as if the core of the iCalendar stuff is mapped in but it just needs tidying up a bit:

- [x]  Add Speaker to the Summary as well as the talk title (nb don't use Attendee field or similar as this is just for group calendar items) - speaker is useful as attendees are often more interested in who is talking rather than the subject
- [x] Part of the location information seems to be missing
- [x] Links are relative not absolute
- [ ] Bit of a wishlist - is there a way of adding a parameter to the request so that items in a .ics feed include a reminder timed to the users requirements (e.g. 30 / 60 / 120 )

**Comment by ahaith** [comment]
First two now implemented. Links I've seen to event pages do seem to be absolute. Could you provide me an example of one which is relative?

**Comment by ahaith** [comment]
ical does theoretically support an alarm. However, I've not had any success trying to make it work.

**Comment by envycontent** [comment]
This is what I downloaded as a single .ics file:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:talks.ox.ac.uk
BEGIN:VEVENT
SUMMARY:WTCHG / Cardiology
DTSTART;VALUE=DATE-TIME:20150604T130000
DTEND;VALUE=DATE-TIME:20150604T140000
UID:/talks/id/20c826db-2055-46dc-8665-14c89f7fc504/
DESCRIPTION:WTCHG: "Genome Sequencing comes to the Clinic"\n\nCardiology:
 "New tools for differentiating hypertrophic cardiomyopathy from its mimics
 "\n\nChair: Prof Sir Peter J Ratcliffe FRS
LOCATION:Headington OX3 9DU
URL:/talks/id/20c826db-2055-46dc-8665-14c89f7fc504/
END:VEVENT
END:VCALENDAR

Importing it into my calendar (Thunderbird/Lightning) I don't actually
see the URL anyway (I think that's the same in Outlook) so wonder
whether URL could be added to the description.

Anne

**Comment by envycontent** [comment]
re alarms - that's interesting. I found a couple of discussions on stackoverflow:

http://stackoverflow.com/questions/7393774/ics-alarms-are-not-appearing-in-google-calendar-or-outlook
http://stackoverflow.com/questions/10259358/ical-valarm-not-registrering/16540934#16540934

depending on what you think, we could maybe incorporate something simple or document how to set up alarms (my reasoning for doing this is that if we facilitated this or some other reminder system, then we can de-prioritize setting up personal reminder systems for the moment)

**Comment by vladigor** [comment]
I've fixed the absolute links.
Removing HighPriority label as the remaining wishlist issue isn't high priority.

**Comment by envycontent** [comment]
I'm going to close this, as the alarm issue isn't important.
