### ISSUE TITLE
browse by the parent/ancestor unit

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#312]
AS A Attendee I WANT TO browse by the parent/ancestor unit of the department or unit talks or series are assigned to SO THAT I can look for all talks or series belonging to a particular department or division

**Comment by ahaith** [comment]
- [ ] Have department links go to the Talks page for that department
- [ ] Include maps link from department page (if not already present)
- [ ] Add link to parent department page on talks (available via mobile oxford place api)

**Comment by vladigor** [comment]
Done
