### ISSUE TITLE
find talks that have already happened

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#314]
AS A Attendee I WANT TO find talks that have already happened SO THAT I can find links to the podcast or other material published after the event

**Comment by envycontent** [comment]
Martin commented: The search provides a way to quickly filter by "Past talks"; 

Also "Browse by Date Range" also meets the criteria here. P-Low and it may be that this story can be flagged as completed.

**Comment by ahaith** [comment]
Can now be done via the browse interface
