### ISSUE TITLE
collect talks into lists

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#316]
AS A Attendee / Series Organizer I WANT TO collect talks into lists SO THAT I can make a manual collection of talks I'm interested in or relevant to a particular topic (that isn't covered by subject headings or other automatic categorizations)

**Comment by envycontent** [comment]
For Phase 2A, this functionality given to Series Organizers only

**Comment by vladigor** [comment]
Done ; will push to dev next week after code review
