### ISSUE TITLE
make a list collaborative

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#318]
AS A Series Organizer I WANT TO make a list collaborative SO THAT so that any series organizer can assign talks to it

**Comment by vladigor** [comment]
Can collaborators alter the list's properties - ie.  its name, description and who may edit it?
Or can they only add/remove talks and series?

**Comment by vladigor** [comment]
Done; will push to dev today.  Have assumed that only the owner of the list may change its properties
