### ISSUE TITLE
get a plain text version

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#325]
AS A Series Organizer / Attendee I WANT TO get a plain text version SO THAT I can cut and paste this into a Word document and format it how I want:

- [x] talk
- [x] series 
- [x] topic 
- [x] collected list
- [x] department
- [x] ~~all above limited by date range~~

**Comment by vladigor** [comment]
To clear up ambiguities:
  I understand the requirement for adding a link on an individual talk page that presents a plain-text version.
  For the series, topic, department and collected list pages:
     Are you expecting a link next to each talk in the page?
     Or a link at the top of the page that renders the whole list of talks as plain text?
     Or both?
     Is the requirement that all of these pages are filterable by date range? (arguably, this is a a separate requirement from the plain text version)

**Comment by envycontent** [comment]
Sorry for the delay answering this.

A link at the top of the page so that all talks in the series, topic,
department etc are rendered (just like an iCal feed) would be the best
option.

re filtering - in the old talks, pages show upcoming talks only with a
link to 'archived' talks i.e. past talks. It makes sense for the plain
text to show only upcoming.

In most cases I don't think there would be huge numbers of upcoming
talks in each list, talks are added about a term in advance.

Anne

**Comment by vladigor** [comment]
Done ; will push to dev next week after code review
