### ISSUE TITLE
Users can track events and event groups in lists

### ISSUE THREAD

**Issue by davbo** [ox-it/talks.ox#33]
Users will all have a default list, and can create additional lists to sort events, for example "Open Day 2014" could be a user created [collaborative] list. While the events are related by a larger ongoing event rather than, for example a conference or seminar series where someone is either attending the conference or enrolled on the seminar series or not.

Known user stories
 - As a user I'd like to add events [and event groups] to my own personal list.
 - As a user I'd like to create a separate list to track events happening on a given theme, for example "Women in Science".
 - As a user I'd like to find and add events to my lists
 - As a user I'd like to remove events from my lists
 - As a user I'd like to discover lists by seeing the lists a given event is already included in

User stories requiring clarifications before development takes place
 - Users can "follow" other lists
 - Users can collaborate on shared lists

**Comment by ahaith** [comment]
Only outstanding item here is discovery by showing existing lists. Now covered by #350
