### ISSUE TITLE
Nuffield Orthopaedic Centre

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#332]
Selecting Nuffield Orthopaedic Centre as a venue throws an error. The talk is saved but not copied to old talks. You should be able to see the error about 16:40 on 19-06-2015.

If the server error message is customizable, it would be helpful to suggest that editors go back to the dashboard and check that the talk is there. A problem arises in that they tend to add the talk again - sometimes numerous times.

**Comment by envycontent** [comment]
see #333

**Comment by ahaith** [comment]
Fixed and deployed to production
