### ISSUE TITLE
When viewing a person page an an anon user, the person edit button is visible

### ISSUE THREAD

**Issue by vladigor** [ox-it/talks.ox#344]
When viewing a person page an an anonymous user, the person edit button is visible.
I suggest this button is only made visible to users with the rights to edit a person.
eg.
/talks/persons/id/cb67e1fb-88ad-428e-b281-d25c30e5f8c6

**Comment by envycontent** [comment]
ooo er oops, yes I agree. We decided that all people would be editable
by all talks editors, because people might appear in different talks.
We've put a warning about editing a person on the edit page and checking
about the possible implications of this.

Anne

**Comment by vladigor** [comment]
Fixed
