### ISSUE TITLE
Lists: authenticated user has option to share a list

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#357]
1 When creating a List or editing the list 'My Collection', an authenticated user (not a talks editor) has the option to share with another talks editor

I don't think this option is actually necessary as our current thinking  is only users with talks editor status can collaborate in creating lists 

If the Other Editors field can be hidden from people who are not talks editors that would do the trick.

2 In Manage Lists, an authenticated user sees 'Lists that I can contribute to' but if they aren't able to share or collaborate in lists (as 1 above) then this wouldn't be relevant

NB: (apologies as you may not have been aware of this doc where we discussed users and permissions a while back):

https://docs.google.com/document/d/1DXZl0D2SbTgPE1kpzbiWh7E9AXoWa4QED2IXaDNHt3A/edit?usp=sharing

**Comment by vladigor** [comment]
Good spot.  Fixed both;  will deploy to dev later today
