### ISSUE TITLE
Lists: odd? behaviour with the Other Editors field

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#358]
Not sure if this is a bug or not.

When logged in as a talks editor:

The Other Editors field in the Add/Edit List seems to behave a bit differently from the way it behaves when editing a talk or a series of talks.

In the talk or series of talks a list of suggestions usually appears as you start typing, in the list edit view, the email address only appears when you have finished typing, before you finish it tells you 'nothing matches your query'. This is a bit disconcerting as it doesn't match the user experience elsewhere.

When just an authenticated user:

Adding an email address to the Other Editors field doesn't work at all (but this doesn't really matter see #357 )

**Comment by ahaith** [comment]
We thought it would be best to avoid giving out all of our users' email addresses through this field, so it only gives a result when a full email address has been entered.
We expect to improve upon this interface, but this was the quickest way to get something functional. We can improve for phase 2A if needed, or leave until 2B

**Comment by envycontent** [comment]
Great, thanks, that makes sense and it is usable - don’t see that there’s a necessity to do further work for Phase 2A. I can document for users. Are you adjusting the field elsewhere (i.e. talks and series) - sorry I could probably find that out for myself.


Anne Bowtell


Web Integration Manager
Medical Sciences Division

**Comment by ahaith** [comment]
No, it's just the email lookup here, outside of the contributors area that doesn't show any suggestions. Everything else should be unchanged.

**Comment by envycontent** [comment]
Ah interesting - does that relate to #357 - can anyone collaborate on a collected list not just editors? 

Anne 


Anne Bowtell


Web Integration Manager
Medical Sciences Division

**Comment by vladigor** [comment]
I don't think this is related to #357.   I've updated #357 and locked down the ability to add editors for authenticated users.

**Comment by envycontent** [comment]
Checked, this works. I'm reassigning this to me, to document the new way the email field works.
