### ISSUE TITLE
Lists: plain text version

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#359]
When a series is added to a list, the iCalendar version shows all the talks in the series.

However, the plain text version merely gives the series name and description rather than listing the talks. As the plain text version is intended to provide an option for people to email a list of upcoming talks to a mailing list etc, it would be good to have all the talks rather than just the name and description.

**Comment by vladigor** [comment]
Should this apply to the HTML view of the list too?  Or should the HTML view just show talks that were added individually?

**Comment by vladigor** [comment]
Done for plain text.  Its trivial to do so for HTML too if desired; however its probably unnecessary (and cluttering) as the user can just click the series name to view the talks in the series.
Will push to dev on Friday.
