### ISSUE TITLE
Lists: View List

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#360]
Please could some more information be added to the View List, for attendees and editors:

1. it would be useful perhaps to have the little world icon next to the list title to indicate that the list is public
2. also helpful to see the editors of the list (we haven't done this for series etc, although actually it would be useful) - I don't know if this could be done by name rather than email
3. I see the logic of showing the individual talks added and then the names of any series added, as it is then possible to have a clear overview of what has been actually added to the list which is good if you're a talks editor.  However, it isn't possible anywhere to get a complete overview of upcoming talks in the list, which is equally useful if you're an attendee. (I get the point that it does clutter things up, but it is harder then to get an idea of what's coming up in the next few days)

**Comment by vladigor** [comment]
Could you add a bit more context to this ticket ... I suspect some text was lost before the bullet points?

**Comment by envycontent** [comment]
Sorry it was a bit garbled and yes I must have missed something off the top. I've rewritten it slightly.

**Comment by envycontent** [comment]
Fab, thanks. 

re 3. Let's go for a list of all upcoming talks - i.e. a complete overview. This would then work very well for Public Lists. An example of a Public List might be, for instance, talks relevant to Athena Swan (women in science and technology) and there might be a selection of talks over a term, plus a lecture series e.g. 'Famous women scientists'. So as a potential attendee it would be far more useful for me to see all the talks in a list.

The talks editors may be able to work out whether they've added an entire series because the series for each talk appears in the listing. If they get seriously confused then we could look at the possibility in a later phase of supplying the separated talk/series listing at the bottom of the Add/Edit view of a List. 

Hope that makes sense.

**Comment by vladigor** [comment]
ok, done.  Will push to dev later today

**Comment by vladigor** [comment]
Pushed to dev
