### ISSUE TITLE
Lists: 'My Collection'

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#361]
Fantastic to have a ready-made 'My Collection' available for authenticated users. I'm just a bit wary about calling it 'My Collection' - if lots of people choose to make their 'My Collection' public there will be lots of random 'My Collection' lists knocking around. 

Is it feasible to name it automatically - e.g. 'John Smith's Collection' ? If not, perhaps we could add some help text to the 'make this list public' field.  E.g. 'Before publishing make sure the list has a distinctive title and description - e.g.: Recommended talks for 3rd Year Biology'

**Comment by vladigor** [comment]
The form already prevents you from making a list public if its called 'My Collection' and suggests that you choose a less generic name, but I agree its a good idea to give a suggestion up front.  
I don't think any automatic name is going to be of much benefit to the user.
Updated locally ; will push to dev on Friday.
