### ISSUE TITLE
iCalendar button

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#364]
It is fantastic to have the plain text icon in various places e.g.: person view, department view. Would it be feasible to have an iCalendar feed button in these places as well? In particular it would be really helpful to have an iCalendar feed for a department and sub-department.

I can see that might be a bit of extra work on the API.

**Comment by vladigor** [comment]
I've added the ical link to the department page by leveraging the api_event_search_ics function in the search api.
Pushed to dev.
I can't really do the same for person ... I could use it to generate an ical feed of the events the person is speaker at, but not ones they are a host/organiser of.
I reckon it would probably be a day or two's work to add ical to person page.

**Comment by envycontent** [comment]
Let's not worry about adding ical to person page - I'll set this ticket to low priority and move to backlog.
