### ISSUE TITLE
Rights for anonymous visitor

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#365]
Is it feasible for an anonymous visitor to be able to see the Browse Talks interface and to see Public Lists?

An anonymous visitor can click through to most of the information anyway (except lists) via the Upcoming Talks.

Sorry, I think the user stories were too neutral on this subject - I wrote them from the perspective of a talks attendee / organiser rather than actual users of Oxford Talks. Earlier discussions about permissions though didn't exclude anonymous users from browsing etc - it would have been helpful if I had added these decisions to the user stories and I will do better in future.

**Comment by vladigor** [comment]
Browse Talks is already usable by anon users - there is a link in the site heading.
View public lists is achievable.  How would you like the user to discover them?  
eg. I could add a link on the homepage or the heading that only appears for anon users. ?

**Comment by envycontent** [comment]
Ah duh. I was looking at new.talks not talks-dev. Sorry!

Thinking about it, if we give people the option to see a list of lists, then we ought also to give them the option to see a list of series and a list of topics. So it becomes a bigger UI thing.  

On the dashboard, there’s a box above the filters which allows the Talks Editor to select a list of Talks | Series | People. Would it be feasible to do the same on the browse interface, perhaps below the filters, a separate box which simply gives links to pages of:  

Series  
Lists

and, if possible:  

Topics  
Departments


Anne Bowtell


Web Integration Manager
Medical Sciences Division

**Comment by vladigor** [comment]
I've added Series and public lists links to the bottom of browse.  
There's no existing listing page for all topics and all departments.  It would probably be around a day's work to add them.

**Comment by envycontent** [comment]
Closing this and putting the outstanding item in a separate issue #374
