### ISSUE TITLE
Importing / Synchronizing iCalendar with OWA

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#367]
I'm using the Web Access version of Outlook on Chrome on a Mac. It appears that you can't import events into OWA but there is the option to specify a URL to sync. I can't get this to work - it sets up the calendar OK but nothing synchronizes. I tried with a Google .ics file as well - so it isn't just our .ics.

Interested if anyone has had a more positive experience?

**Comment by vladigor** [comment]
It doesn't sound like this is possible.
http://answers.microsoft.com/en-us/office/forum/office_2010-outlook/how-do-i-open-ics-files-in-outlook-web-access/c765c07e-20ae-44b5-baa4-1d4f94fdfbeb?auth=1

**Comment by envycontent** [comment]
I'll document
