### ISSUE TITLE
Odd display issues in Safari

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#368]
Safari 8.0.8 on Yosemite

I'm seeing some odd display issues:

1. minor - calendar icon isn't aligned to the right on the home page - pushed down a line instead
2. bit more major - Browse Talks - grid lines on the table don't align with the listing
![screen shot 2015-09-01 at 10 03 48](https://cloud.githubusercontent.com/assets/2123909/9600158/47432cda-5091-11e5-9c80-c71023ace9ba.png)

**Comment by ahaith** [comment]
Looks like the 'inline-flex' display type doesn't work in Safari.

**Comment by vladigor** [comment]
Fixed and pushed to dev
