### ISSUE TITLE
Tweaks to the Browse Page

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#370]
A colleague and I had a look at the browse talks page yesterday. We thought that, in a later phase, it should get some user testing and we didn't want to pre-empt that. Here are a few possible tweaks though 

1. When we first visit the page it can be a bit confusing because it doesn't look as if there are many talks - we don't notice the filter. Could we either mention the filter at the bottom of the page (e.g. For more talks extend the end date in the filters on the left) or could we extend the end date to 8 weeks - which would cover a term (I noticed that this would be about 600 talks at least) or could we somewhere indicate the date range of the talks being shown i.e. showing talks from X to X.

2. Would it possible to make the dates displayed in the filter a bit more user friendly - e.g. dd/mm/yy ?

3. Could we move 'venue' to below 'series'  in the filters, as department and series are more likely to be used?

4. Could we move 'View All' to above the filters?

**Comment by vladigor** [comment]
Handling trivial changes ...
1. I've changed the default end date to 8 weeks
3. Done
4. Done

Changing date format is tricky ... maybe a few hours work?  Similarly, if we added text to the top of the browse list to highlight the date range the tricky part would be reformatting the dates.

**Comment by envycontent** [comment]
Fab, thanks. 2. isn't really a bit issue. I'll open another ticket and put it as a low priority enhancement.

**Comment by envycontent** [comment]
closed and see #372 for the remaining item
