### ISSUE TITLE
Text version: ordering of fields

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#375]
I figured it might be sensible to order fields as per the text layout on the old Oxford Talks - as per http://talks.ox.ac.uk/show/text/12504

This omits the field label for each field and the order is this:

Title
Special Message
Speaker(s)
Date and Time
Location
Oxford Talks URL

The main aim of the text version is to have something that can be dropped into a once a week email. So keeping the number of fields to the very basics means that the recipient can scan the information quickly and follow up using the link.

If it is possible then it would be great to group the talks by day, as per the example above.

**Comment by vladigor** [comment]
Should this apply for all plain text pages?  (ie. single talk, series, dept, person)?

**Comment by envycontent** [comment]
If its feasible to do the abbreviated version for anything that gives multiple talks, but to keep the extended version for single talks that would be great.

**Comment by envycontent** [comment]
Closing this as I believe it has been done.
