### ISSUE TITLE
Embed template URLS for old talks

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#378]
if new.talks.ox.ac.uk becomes talks.ox.ac.uk and the current talks.ox.ac.uk becomes old.talks.ox.ac.uk, then the following URLs will need to be redirected to old.talks.ox.ac.uk

NB all are likely to be followed by a list of a parameters

http://talks.ox.ac.uk/show/table/[seriesid]
http://talks.ox.ac.uk/show/minimalist/[seriesid]
http://talks.ox.ac.uk/show/detailed/[seriesid]
http://talks.ox.ac.uk/show/bulletin/[seriesid]
http://talks.ox.ac.uk/show/simplewithlogo/[seriesid]
http://talks.ox.ac.uk/show/oneday/[seriesid]
http://talks.ox.ac.uk/show/text/[seriesid]
http://talks.ox.ac.uk/show/xml/[seriesid]
http://talks.ox.ac.uk/show/rss/[seriesid]
http://talks.ox.ac.uk/show/ics/[seriesid]
http://talks.ox.ac.uk/show/json/[seriesid]

https://talks.ox.ac.uk/feeds/table/[seriesid]
https://talks.ox.ac.uk/feeds/minimalist/[seriesid]
https://talks.ox.ac.uk/feeds/detailed/[seriesid]
https://talks.ox.ac.uk/feeds/bulletin/[seriesid]
https://talks.ox.ac.uk/feeds/simplewithlogo/[seriesid]
https://talks.ox.ac.uk/feeds/oneday/[seriesid]
https://talks.ox.ac.uk/feeds/text/[seriesid]
https://talks.ox.ac.uk/feeds/xml/[seriesid]
https://talks.ox.ac.uk/feeds/rss/[seriesid]
https://talks.ox.ac.uk/feeds/ics/[seriesid]
https://talks.ox.ac.uk/feeds/json/[seriesid]

(feeds is an alias for ‘show’ working around the webauth prompt)

**Comment by ahaith** [comment]
These all now forward on to the standard series for the relevant list/series.
It might be possible to map some of them to specific new routes (e.g. ics, text), but I haven't done so for now.
