### ISSUE TITLE
Organizing Department link - gives server error

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#395]
Some organising department links give a server error e.g.:

https://new.talks.ox.ac.uk/talks/department/id/oxpoints%3A23232803

others seem to work fine:

https://new.talks.ox.ac.uk/talks/department/id/oxpoints%3A23232646

**Comment by envycontent** [comment]
see also 

https://new.talks.ox.ac.uk/talks/department/id/oxpoints%3A23232441  (St Cross College)

could this be where the unit/department/college isn't part of any other unit/department or college

**Comment by ahaith** [comment]
The moxie places API returns an error when we query it for the descendant organisations for some places.
We should catch this if it occurs, but we should also address the issue in the places API.

**Comment by ahaith** [comment]
http://api.m.ox.ac.uk/places/oxpoints:23232803/organisation-descendants
