### ISSUE TITLE
Error when adding a talk to a list

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#419]
Adding an existing talk to a list throws an error - although the talk is added to the list. 

The problem occurred with this list:

https://new.talks.ox.ac.uk/user/lists/id/8c5df4b0-f99e-4ba8-aff4-8fc67cc353a7/

c 8.10am 08-04-2016

**Comment by ahaith** [comment]
Here is the sentry log for the error. http://sentry.oucs.ox.ac.uk/oxtalks/staging/group/146331/

I suspect it may be related to the recent outage of the mobile Oxford API. Will investigate.

**Comment by envycontent** [comment]
Closing as we think this is fixed.
