### ISSUE TITLE
Error when viewing the 'mytalks' url if not logged in

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox#475]
Visit https://talks.ox.ac.uk/user/mytalks without being logged in and there is a 500 error.
This might happen if the page is bookmarked or refreshed after session expired.

Should be easily fixed by annotating the relevant view function with an @login_required

**Comment by ahaith** [comment]
This might be a good one for @homopluvial or @zen-nomind to fix and deploy.

**Comment by birniefoxford** [comment]
Fixed by @homopluvial in commit **3f0ff947a3dab21bd35baa54a6adc8f97dda71c0**
