### ISSUE TITLE
Assigning a user as a contributor to a collection

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#477]
This is a little bit urgent as we are currently in 1st week and some departments are just starting with Oxford Talks and will make some use of collections.

If you add james.baldwin@politics.ox.ac.uk as a contributor to a collection e.g.:

https://talks.ox.ac.uk/user/lists/id/998f092f-0c71-4af0-9201-f35cd4f9dfe2/

and then save

Finlay Birnie is then shown as the contributor on the collection page. James also reports that he doesn't see the collection in his dropdown list (which suggests that Finlay is actually assigned to the collection). 

Two things I've noticed:

It *doesn't* happen if you assign James as an editor of a series
James and Finlay signed up within two minutes of each other and so are next to each other on the list of users.
If you try to sign Finlay up to the collection then it selects the next in the list - Philip Saunders
If you add someone much earlier in the list - e.g. Nicole Harris it works fine
 

(I have taken temporary ownership of these two collections, just to try to see what it happening)

**Comment by ahaith** [comment]
@homopluvial @birniefoxford @zen-nomind. Any chance one you could investigate this quite soon?
I think it may just be coincidence that Finlay's name popped up.

**Comment by envycontent** [comment]
I'm around today and tomorrow and can skype / phone if necessary, if you need any further info
