### ISSUE TITLE
New collection owners are unable to edit their collections

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#482]
A couple of fairly recent Talks Editors can create a collection, but get a permission denied message when they next try to edit the collection (by clicking the edit button).

I haven't had a problem with this myself, so can't replicate it.

**Comment by ahaith** [comment]
@birniefoxford @homopluvial Potentially related to the issue you fixed recently?

**Comment by birniefoxford** [comment]
This should be fixed by my changes for PR #484.

**Comment by envycontent** [comment]
I checked with the users last week and they said that it had been solved. Thanks very much indeed.
