### ISSUE TITLE
Big Data Institute

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#483]
The Big Data Institute has been added to Oxpoints but isn't appearing on drop down lists for venues and organising units. We've also noticed that it isn't appearing on maps.ox.ac.uk

**Comment by ahaith** [comment]
@birniefoxford Sounds like another oxpoints import is needed to m.ox.

**Comment by birniefoxford** [comment]
@envycontent I've imported the oxpoints data and the BDI is showing as a department choice on Talks.ox, but not as a venue. For some reason the BDI 'Building' from Oxpoints hasn't made it into moxie.

**Comment by birniefoxford** [comment]
@envycontent I think I know why; it does come up if you type 'BDI'. I was trying 'Big'. This is probably because the entity has 2 preferred names.

**Comment by alexsdutton** [comment]
I've just fixed the two-preferred-name issue in OxPoints. I'll wait a couple of minutes then suck it into data.ox

**Comment by birniefoxford** [comment]
Looks fine here: https://oxpoints.oucs.ox.ac.uk/id/52493443.json

But here is the record after I've used moxie to import it to SOLR:

`{
        "identifiers": [
          "oxpoints:52493443"
        ],
        "meta_precedence": 10,
        "child_of": [
          "oxpoints:58403295",
          "oxpoints:52395838"
        ],
        "address": "Old Road Campus OX3 7LF",
        "id": "oxpoints:52493443",
        "name": "BDI",
        "name_sort": "BDI",
        "type_name": [
          "Building"
        ],
        "location": "51.752846,-1.214612",
        "type": [
          "/university/building"
        ],
        "type_exact": [
          "/university/building"
        ],
        "_version_": 1567202193898995700
      }`

**Comment by alexsdutton** [comment]
data.ox now has the fixed BDI building data anyway :-)

**Comment by birniefoxford** [comment]
Great. Now working for both venues and departments.

**Comment by envycontent** [comment]
Perfect! Thanks!

Anne

Anne Bowtell | Web Integration Manager
Medical Sciences Division | University of Oxford | Level 3, John Radcliffe Hospital, Oxford, OX3 9DU
anne.bowtell@medsci.ox.ac.uk<mailto:anne.bowtell@medsci.ox.ac.uk> | +44 (0)1865 617120 | www.medsci.ox.ac.uk<http://www.medsci.ox.ac.uk/> | @OxfordMedSci<http://www.twitter.com/oxfordmedsci>


On 12 May 2017 at 16:32:47, birniefoxford (notifications@github.com<mailto:notifications@github.com>) wrote:

Great. Now working for both venues and departments.
