### ISSUE TITLE
Names of multiple speakers listed in plain text, but not html, view

### ISSUE THREAD

**Issue by jamesscottbrown** [ox-it/talks.ox#485]
If an event has multiple speakers, then a list of their names is given in the plain text view ([example](https://new.talks.ox.ac.uk/talks/id/ad332374-dd46-4d86-8bdc-3e1bc1f248e1/?format=txt)), but the HTML view ([example](https://new.talks.ox.ac.uk/talks/id/ad332374-dd46-4d86-8bdc-3e1bc1f248e1/)) simply says "Various Speakers", which is unhelpful.

**Comment by envycontent** [comment]
I've added this to my list of things to document to clarify how it behaves. Actually you had the various speakers option ticked which overrides the actual list of speakers (and probably ought to do the same in the text view). I've cleared the option box.

**Comment by birniefoxford** [comment]
This happens because the plain text template for viewing an event doesn't account for the 'various speakers' option whereas the HTML template does - working on a commit for this now.
