### ISSUE TITLE
Error with a calendar feed

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#488]
https://talks.ox.ac.uk/api/series/535faa11-a7a5-4833-a2e5-5e3d033ad363.ics

A user has reported an error with the above feed - he says that other series work fine. We just get a server error message so I can't see if there is anything in particular creating the problem.

**Comment by birniefoxford** [comment]
I have a fix for this - there was an event in the series whose location was a reference to a deleted oxpoint. See pull request: #489

**Comment by birniefoxford** [comment]
PR reviewed, merged and deployed - calendar item now downloads properly.
