### ISSUE TITLE
Making iCal feed more informative

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#494]
Feature request from user 

I was wondering if it
would be possible at all to add the speaker(s) name(s) + affiliation to
the SUMMARY string that is being output by the ICS/VCALENDAR export
links. Currently the summary string is equal to the talk title only. See
for example the embedded calendar here
http://www.neurotheory.ox.ac.uk/events_ONTF.html

If the summary was a combination of Speaker, Affiliation and Title, I
feel calendar output would be more informative. Since many of my
colleagues including myself are using this feature to directly import
Seminar Series calendars into their personal agendas such as Outlook and
Google, this feature would be extremely helpful.

**Comment by birniefoxford** [comment]
I've implemented this in pull request #496.

**Comment by birniefoxford** [comment]
Pull request tested and merged.
