### ISSUE TITLE
Request for series name to be included in plain text export

### ISSUE THREAD

**Issue by nh19** [ox-it/talks.ox#502]
We have received the following request on oxtalks-contact@it.ox.ac.uk 

We are making use of the plain text version of OxTalks information but it doesn't seem to include series names. Is there a way this could be added to the plain text export?

**Comment by birniefoxford** [comment]
Sorry for getting to this late - the series name is already included in the plain text view for events, labelled "Part of: ". e.g. on this event:

https://talks.ox.ac.uk/talks/id/9aac6fef-3cc4-4bfa-9027-f5b1027f4b24/?format=txt
