### ISSUE TITLE
[celery task] Updating old talks from new talks

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#54]
I've looked at the tables and written something up here. 

https://docs.google.com/document/d/1aqKcXxCGHwcpZa0d822T4bNcMh_Nry8IOR6oQdZxX-g/edit?usp=sharing

I think we could get away with updating just two tables - the Lists and the Talks tables (note the lists table also includes venues). This might involve one or two tweaks to the templates but nothing major. I don't think we would have to update any of the many-to-many link tables or the User tables. 

I've put a few notes at the bottom of the document. 

If it were possible to match primary keys in the new talks database with the IDs in the old talks database this would make updating much simpler. The aggregator isn't able to do this and, as a result, we sometimes get lots of duplicates, incomplete or deleted items, especially when the it breaks. The aggregator tends to break on odd characters or encoding, so I imagine we'd be able to control for that as well.

**Comment by martinfilliau** [comment]
Done in #84
