### ISSUE TITLE
Update API to filter events

### ISSUE THREAD

**Issue by martinfilliau** [ox-it/talks.ox#68]
Current API needs to be extended to add the following filtering capabilities:
* [x] get events for a given **event group**, by group event slug (pending #66)
* [x] get events for one or a list of departments (using multiple times the same GET parameter) 
* [x] get events for department only or departments and descendants (e.g. all departments under the Medical Science Division)
* [x] get events for one or a list of venues (using multiple times the same GET parameter)
* [ ] get events for venues only or venues and descendants (e.g. all venues under the Science Area)
* [x] get events for one or a list of topics (using multiple times the same GET parameter), by the FAST URI
* [x] get events for a given date range -- specific format to be discussed, should also provide some "dynamic" shortcuts such as "from=now, today/upcoming/in the past"
* [x] get by speaker (role speaker for events), pending #66

**Comment by envycontent** [comment]
closing this and adding the single incomplete item to the API wishlist
