### ISSUE TITLE
Demo widget for the API

### ISSUE THREAD

**Issue by martinfilliau** [ox-it/talks.ox#70]
Advanced version could be an "embed" page that could be embedded in an iframe, details need to be discussed but the aim is to ease the use of the API for common use cases.

**Comment by martinfilliau** [comment]
See https://github.com/ox-it/talks.ox-js-widget

**Comment by envycontent** [comment]
I'm testing this out with a view to documenting it for 'web managers' like me. However, I'm getting a 404 response (have changed the URL stem to the current development server URL).

**Comment by ahaith** [comment]
There was an issue on the master branch which meant the search wasn't working. I've fixed this now and deployed.
It might still not be possible to view it from a local html page however, due to the browser's cross-origin restrictions.

**Comment by envycontent** [comment]
Thanks, I'll experiment further.

Anne

**Comment by envycontent** [comment]
Hooray - does seem to be working! Presumably because of this #190 ?

**Comment by ahaith** [comment]
OK Great. I guess you're viewing via http:// and not just directly opening the html file.
N.B. I'm still expecting there should be some tweaks to the coding interface for this, and also we probably want to add some default styling for the results. Let me know if you've any specific thoughts on this after trying it out.

**Comment by envycontent** [comment]
Actually the latter. I'll post issues as they arise - some just about to
appear.
